### PR TITLE
1 climate matching rework

### LINKED ISSUE #1: Use higher ress tiffs to do climate matching
https://ndownloader.figshare.com/files/12407516 => download 1x1km tiffs 0p0083 (niet conf)
https://www.rdocumentation.org/packages/tiff/versions/0.1-6/topics/readTIFF => to read tiffs
The maps are stored in GeoTIFF format as unsigned 8-bit integers. The maps are referenced to the World Geodetic Reference System 1984 (WGS 84).

_Originally posted by @SanderDevisscher in https://github.com/inbo/easin/issues/39#issuecomment-809377485_

### LINKED ISSUE #7: Determine a logical gbif records threshold
In the current climate matching outputs (see [future](https://github.com/inbo/riparias-prep/blob/a1f20d61681c3941b1858b38b2b29c4339571b92/data/output/data_overlay_future_10km.csv) & [present](https://github.com/inbo/riparias-prep/blob/a1f20d61681c3941b1858b38b2b29c4339571b92/data/output/data_overlay_present_10km.csv) - data overlays) contain all species with at least 1 record in the belgian climate zones (Cfa, Cfb & Dfb). A single/low number of record(s) can be an error, fluke, etc.... and can best be excluded from the list. 

But a what number do we place the threshold ?

### PR DESCRIPTION
**Pull request by SanderDevisscher**
@adrienlatli @timadriaens 

This PR fixes #1 & fixes #7

I've downloaded the approx. 10km (0.083°) resolution tiffs from https://ndownloader.figshare.com/files/12407516.
Converted these to esri shp using the convert from [raster to polygon](https://desktop.arcgis.com/en/arcmap/latest/tools/conversion-toolbox/raster-to-polygon.htm) tool from the conversion - toolbox.

Using these shapes I did a rerun of the script resulting in [252 species](https://github.com/inbo/riparias-prep/blob/a1f20d61681c3941b1858b38b2b29c4339571b92/data/output/data_overlay_future_10km.csv) for the future climate (Cfa & Cfb) and [119 species](https://github.com/inbo/riparias-prep/blob/a1f20d61681c3941b1858b38b2b29c4339571b92/data/output/data_overlay_present_10km.csv) for the current climate (Cfb & Dfb).

~After this PR its up to you guys to determine a logical threshold for the number of gbif records in a climate zone (see issue #7).~

After applying the thresholds (at least 90 gbif records with at least 20% climate match) the script results in [30 species](https://github.com/inbo/riparias-prep/blob/f2efaa354e7b23613e4e940243cf545c80b4e230/data/output/data_overlay_future_10km.csv) for the future climate and [17 species](https://github.com/inbo/riparias-prep/blob/f2efaa354e7b23613e4e940243cf545c80b4e230/data/output/data_overlay_present_10km.csv) for the current climate.

### CODE REVIEW

**Comment by SanderDevisscher** [comment]
I'll implement the record threshold (see #7) in this branch

**Review by timadriaens — APPROVED** [review]

**Comment by SanderDevisscher** [comment]
@timadriaens @adrienlatli can you take a look at the new results and approve (merge and delete branch) if the PR is ok ?

**Comment by SanderDevisscher** [comment]
Future changes to the script (ea thresholds, filters, ...) or additions/deletions to the whitelist should be listed in new issues.

**Comment by timadriaens** [comment]
looking good, I merged

**Pull request merged**
