### PR TITLE
27 update riparias baseline

### LINKED ISSUE #27: Update riparias Baseline
See https://github.com/inbo/fis-projecten/issues/136

### LINKED ISSUE #29: Create interactive leaflet for zwalmvallei
Temporele component met slider (2000 - now)

_Originally posted by @SanderDevisscher in https://github.com/inbo/fis-projecten/issues/136#issuecomment-853830935_

### PR DESCRIPTION
**Pull request by SanderDevisscher**
Fixes #27 
Fixes #29 

https://iasspeciesdashboard.shinyapps.io/Riparias-baseline-maps/?_ga=2.2735920.1699838300.1623651778-1489601090.1593499425
werd upgedatet 

daarnaast werd een nieuwe interactieve kaart gemaakt voor de perimeter van de zwalmvallei die liesbeth heeft doorgestuurd. 
zie https://iasspeciesdashboard.shinyapps.io/exoten-in-zwalmvallei/

### CODE REVIEW

**Comment by SanderDevisscher** [comment]
Adding 2 species to species list + rerun

**Comment by SanderDevisscher** [comment]
@timadriaens ik ga morgen een nieuwe update doen van de baseline/zwalm vallei daarna zet ik de PR terug open voor review.

**Comment by SanderDevisscher** [comment]
@timadriaens zowel de [baseline](https://iasspeciesdashboard.shinyapps.io/Riparias-baseline-maps/?_ga=2.21990139.1324873201.1624451876-1489601090.1593499425) als de [zwalm](https://iasspeciesdashboard.shinyapps.io/exoten-in-zwalmvallei/) kaartjes werden upgedatet. 

Keur je deze PR en de [spiegel PR](https://github.com/inbo/easin/pull/45) in de EASIN repo goed als alles in orde is?

**Review by timadriaens — CHANGES_REQUESTED** [review]
The two new crayfish are lacking from the legend (marbled crayfish and Procambarus zonangulus/acutus)

**Comment by SanderDevisscher** [comment]
> The two new crayfish are lacking from the legend (marbled crayfish and Procambarus zonangulus/acutus)

I probably found the cause for these species lacking from the Riparias shinyapp. I do a filter based on a nameserver which was lacking these species. 

Adding, _Procambarus virginalis_, which is named **marbled crayfish** in english to the nameserver does create a conflict with _Procambarus fallax_ which is also named **marbled crayfish** in english. Alternatively _Procambarus fallax_ is also named **Slough Crayfish** or **Deceitful Crayfish**. I suggest using 1 of these names for the shinyapp. 

@timadriaens which of the alternative names should I use ?

**Comment by timadriaens** [comment]
@SanderDevisscher Procambarus fallax is no longer the same as Procambarus virginalis. The species listed on the Union List in 2016 was originally **Procambarus fallax f. virginalis** (the parthenogenetic form of P. fallax), but so the taxonomy has changed and the marbled crayfish is now calle Procambarus virginalis. Slough crayfish is P. fallax (sensu novo) so that name is incorrect and confusing. Can we alter the name for fallax on the nameserver so that the shiny displays "marbled crayfish"?

**Comment by SanderDevisscher** [comment]
@timadriaens currently both _Procambarus fallax_ & _Procambarus virginalis_ are named **marbled crayfish**.

see https://docs.google.com/spreadsheets/d/15f17hXE9ZyUxEe2xA0seKs0CSibgYJdkaWcnmVoI1yY/edit#gid=0

**Review by timadriaens — APPROVED** [review]
looking great now, missing Procambarus spp. have been added

**Pull request merged**
