### PR TITLE
32 baseline check

### LINKED ISSUE #32: updated baseline check
@adrienlatli checked the updated baseline (which now looks good for the crayfish spp.):

- [ ] some points have disappeared from the last baseline (in red on the map) (+/-20) only in Flanders. It 's mainly plant observations like ludwigia or hydrocotyle. These need to be checked why they disappeared from the baseline.
- [ ] new observations of this year (2021) have been added. These can be visible on the map but need to be separated from the baseline as this only takes into account the observations made until December 31, 2020.
 
For Wallonia the baseline is OK and validated.
@SanderDevisscher can we check and solve these issues?

image003

### PR DESCRIPTION
**Pull request by SanderDevisscher**
Fixes #32 
Data from VMM was missing due to a error in the easin flow fixed in [PR #48](https://github.com/inbo/easin/pull/48). The same PR also contains a rerun of all the scripts. 

Additionally a new [baseline export](https://github.com/inbo/riparias-prep/blob/32_baseline_check/data/spatial/baseline/baseline.geojson) has been added to the maps_prep script.  This geojson contains all observations up to 2020-12-31 within the riparias perimeter.

### CODE REVIEW

**Comment by adrienlatli** [comment]
@SanderDevisscher : hi Sander. Thank you for your update. I can't download a csv version of the final baseline (I am unable to turn the txt file into a workable csv). Can you send it to me ?
thank you so much

**Comment by SanderDevisscher** [comment]
@adrienlatli I've added a standard .csv export of the baseline data. 

Can you try opening this file ? [baseline_data.csv](https://github.com/inbo/riparias-prep/raw/32_baseline_check/data/output/baseline_data.csv)

**Comment by adrienlatli** [comment]
@SanderDevisscher 
Hello, I have checked the new baseline. This time, all is going well for Flanders but for Wallonia many points have disappeared (640; orgin  SPW-DEMNA database).
It's quite strange because in the baseline of July all the Walloon points were present ...

**Comment by SanderDevisscher** [comment]
@adrienlatli are the points also missing if you ignore the source ?

**Comment by adrienlatli** [comment]
@SanderDevisscher 
Not sure to well understanding your question.
I downloaded the current csv and i Have only 5736 observations versus 6376 for the csv made in jully (without 2021 points). The data owners of the miising points is the SPW-DEMN

**Comment by SanderDevisscher** [comment]
Ok I'll look into it

**Comment by SanderDevisscher** [comment]
the website has been updated.

**Comment by SanderDevisscher** [comment]
@adrienlatli I did some enhancements concerning the occurence status of the observations to allow future logging of absences (none yet, vmm data is displayed currently as NA). Can you look at the app to see if no errors have occurred. ifnot you can approve this PR.

**Comment by SanderDevisscher** [comment]
@adrienlatli I assume you wanted to approve this PR? correct ?

**Comment by adrienlatli** [comment]
Yes, but I have only few experience with Github sorry if I made a mistake

**Comment by SanderDevisscher** [comment]
> Yes, but I have only few experience with Github sorry if I made a mistake

No problem

**Pull request merged**
